package beans;
// Generated May 16, 2015 12:13:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Complaint generated by hbm2java
 */
public class Complaint  implements java.io.Serializable {


     private Integer cid;
     private Department department;
     private String type;
     private String description;
     private String launchname;
     private String cnic;
     private String image;
     private String status;
     private String location;
     private Date launchdate;
     private int positiveendorse;
     private int negativeendorse;
     private Set tracks = new HashSet(0);
     private Set endorsements = new HashSet(0);

    public Complaint() {
    }

	
    public Complaint(Department department, String type, String description, String launchname, String cnic, String image, String status, String location, Date launchdate, int positiveendorse, int negativeendorse) {
        this.department = department;
        this.type = type;
        this.description = description;
        this.launchname = launchname;
        this.cnic = cnic;
        this.image = image;
        this.status = status;
        this.location = location;
        this.launchdate = launchdate;
        this.positiveendorse = positiveendorse;
        this.negativeendorse = negativeendorse;
    }
    public Complaint(Department department, String type, String description, String launchname, String cnic, String image, String status, String location, Date launchdate, int positiveendorse, int negativeendorse, Set tracks, Set endorsements) {
       this.department = department;
       this.type = type;
       this.description = description;
       this.launchname = launchname;
       this.cnic = cnic;
       this.image = image;
       this.status = status;
       this.location = location;
       this.launchdate = launchdate;
       this.positiveendorse = positiveendorse;
       this.negativeendorse = negativeendorse;
       this.tracks = tracks;
       this.endorsements = endorsements;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLaunchname() {
        return this.launchname;
    }
    
    public void setLaunchname(String launchname) {
        this.launchname = launchname;
    }
    public String getCnic() {
        return this.cnic;
    }
    
    public void setCnic(String cnic) {
        this.cnic = cnic;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Date getLaunchdate() {
        return this.launchdate;
    }
    
    public void setLaunchdate(Date launchdate) {
        this.launchdate = launchdate;
    }
    public int getPositiveendorse() {
        return this.positiveendorse;
    }
    
    public void setPositiveendorse(int positiveendorse) {
        this.positiveendorse = positiveendorse;
    }
    public int getNegativeendorse() {
        return this.negativeendorse;
    }
    
    public void setNegativeendorse(int negativeendorse) {
        this.negativeendorse = negativeendorse;
    }
    public Set getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Set tracks) {
        this.tracks = tracks;
    }
    public Set getEndorsements() {
        return this.endorsements;
    }
    
    public void setEndorsements(Set endorsements) {
        this.endorsements = endorsements;
    }




}


