package beans;
// Generated Apr 28, 2015 11:49:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private int did;
     private String dname;
     private Set tracks = new HashSet(0);
     private Set complaints = new HashSet(0);
     private Set userses = new HashSet(0);

    public Department() {
    }

	
    public Department(int did, String dname) {
        this.did = did;
        this.dname = dname;
    }
    public Department(int did, String dname, Set tracks, Set complaints, Set userses) {
       this.did = did;
       this.dname = dname;
       this.tracks = tracks;
       this.complaints = complaints;
       this.userses = userses;
    }
   
    public int getDid() {
        return this.did;
    }
    
    public void setDid(int did) {
        this.did = did;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public Set getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Set tracks) {
        this.tracks = tracks;
    }
    public Set getComplaints() {
        return this.complaints;
    }
    
    public void setComplaints(Set complaints) {
        this.complaints = complaints;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


