package beans;
// Generated May 16, 2015 12:13:57 AM by Hibernate Tools 4.3.1



/**
 * Endorsement generated by hbm2java
 */
public class Endorsement  implements java.io.Serializable {


     private Integer keyinc;
     private Complaint complaint;
     private String lname;
     private String description;
     private String cnic;
     private boolean endorsetype;

    public Endorsement() {
    }

    public Endorsement(Complaint complaint, String lname, String description, String cnic, boolean endorsetype) {
       this.complaint = complaint;
       this.lname = lname;
       this.description = description;
       this.cnic = cnic;
       this.endorsetype = endorsetype;
    }
   
    public Integer getKeyinc() {
        return this.keyinc;
    }
    
    public void setKeyinc(Integer keyinc) {
        this.keyinc = keyinc;
    }
    public Complaint getComplaint() {
        return this.complaint;
    }
    
    public void setComplaint(Complaint complaint) {
        this.complaint = complaint;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCnic() {
        return this.cnic;
    }
    
    public void setCnic(String cnic) {
        this.cnic = cnic;
    }
    public boolean isEndorsetype() {
        return this.endorsetype;
    }
    
    public void setEndorsetype(boolean endorsetype) {
        this.endorsetype = endorsetype;
    }




}


